In [1]:
## Sesi 4
## Numpy

In [2]:
import numpy as np

In [3]:
firstarray =np.array([1,2,3,4,5])

In [4]:
firstarray

array([1, 2, 3, 4, 5])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.empty(3)

array([1., 1., 1.])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [15]:
np.arange(2,10,3) #Start, Stop , Step

array([2, 5, 8])

In [17]:
##Add, Rmove, Sort

In [27]:
arr= np.array([1,2,3,5,6,7,8,])

In [28]:
np.append(arr, [1,2,3])

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [29]:
arr

array([1, 2, 3, 5, 6, 7, 8])

In [30]:
np.delete(arr,2)

array([1, 2, 5, 6, 7, 8])

In [31]:
np.delete(arr, 1)

array([1, 3, 5, 6, 7, 8])

In [32]:
np.sort(arr)

array([1, 2, 3, 5, 6, 7, 8])

In [33]:
## Shape and Size

In [37]:
array_exam=  np.array([[[0,1,2,3],[4,5,6,7]],
[[0,1,2,3],[4,5,6,7]],
[[0,1,2,3],[4,5,6,7]]])

In [38]:
print(array_exam)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [39]:
array_exam.ndim

3

In [40]:
array_exam.size

24

In [41]:
array_exam.shape

(3, 2, 4)

In [42]:
## Reshape

In [43]:
a = np.arange(6)

In [45]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [54]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
## Convert 1D to 2D

In [56]:
a.shape

(6,)

In [58]:
a2 = a[np.newaxis]

In [59]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [60]:
a2.shape

(1, 6)

In [61]:
a2[np.newaxis]

array([[[0, 1, 2, 3, 4, 5]]])

In [62]:
a2.shape

(1, 6)

In [64]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [65]:
b=a[:,np.newaxis]

In [66]:
b.shape

(6, 1)

In [68]:
b3=np.expand_dims(a, axis=1)

In [69]:
b3.shape

(6, 1)

In [70]:
b4 = np.expand_dims(a, axis=0)

In [71]:
b4

array([[0, 1, 2, 3, 4, 5]])

In [72]:
## Indexing and Slicing

In [73]:
a

array([0, 1, 2, 3, 4, 5])

In [74]:
print(a[2])

2


In [75]:
a[0:3]

array([0, 1, 2])

In [76]:
a[2:]

array([2, 3, 4, 5])

In [77]:
a[:2]

array([0, 1])

In [87]:
newArray= np.array([
    [1,2,3,4], [5,6,7,8], [9,11,12,13]
])

In [88]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [90]:
newArray[newArray<12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [91]:
newArray[(newArray>2)& (newArray<12)]

array([ 3,  4,  5,  6,  7,  8,  9, 11])

In [92]:
## Create ign array form existing data

In [93]:
arr=np.arange(1,11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr1=arr[2:8]

In [99]:
arr1

array([3, 4, 5, 6, 7, 8])

In [102]:
arr2=arr[2:8]

In [103]:
np.vstack((arr1, arr2))

array([[3, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7, 8]])

In [104]:
np.hstack((arr1, arr2))

array([3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8])

In [105]:
data =np.array([1,2])

In [106]:
ones = np.ones(2)

In [107]:
data+ones

array([2., 3.])

In [108]:
data*ones

array([1., 2.])

In [110]:
a.sum()

15

In [114]:
c = np.array([[1,2],[2,3]])

In [115]:
c.sum()

8

In [116]:
## Broadcasting

In [120]:
data =np.array([[1,2,3,4,5,6,7] , [8,9,10,11,12,13,14], [15,16,17,18,19,20,21]

])

In [121]:
data

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [122]:
data.min()

1

In [123]:
data.max()

21

In [127]:
data.mean()

11.0

In [128]:
## Matrice

In [ ]:
np.array([[1,2],[3,4]])